[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_nft_marketplace = "4ACXJjwsV5gWRFZTzS7AYpEtf8r977RrD8QEZQgwP39x"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
